### ISSUE TITLE
Citizen Jobs

### ISSUE THREAD

**Issue by u04576617** [COS214-Project-2024/WorksOnMyMachineTeam#20]
- [x] Citizens can have jobs
- [x] Citizens will actively seek jobs if they are unemployed
- [x] Employment status should affect their emotional state

**Comment by u04576617** [comment]
@Amber21457752 @NicholasDobson 
I think for jobs citizens should have a specific building they're assigned to work at. So different buildings can have different numbers of employees.

We could have each citizen have a pointer to the building they work at (which would be my task), and then the buildings would need to have a list of pointers to their employees just to keep track of stuff. We don't need to really do anything with this, it's just to keep track with how many people are employed where (which of course falls in your section).

Let me know what you guys think?

Maybe there would we a registerEmployee(Citizen*) function that citizens can call to become an employee or something?

**Comment by Amber21457752** [comment]
I like this idea and it shouldn't be too difficult to implement. It's a good way to keep track and it shouldn't affect the system to much. i will go in and implement it to see how it works then get back to you

**Comment by Thunder2505** [comment]
I added an employees vector to each building, with a job capacity, so in the simulation engine we can make them look for buildings with open positions. We can also add the building pointer to the employee if we want to, so each employee also knows where it works...

**Comment by Amber21457752** [comment]
> Maybe there would we a registerEmployee(Citizen*) function that citizens can call to become an employee or something?

So this has already been implemented basically?

**Comment by u04576617** [comment]
@Thunder2505 Do we need it in simulation engine? I can add that to the citizens as well, as they would need to "decide" what to do every now and then. I can add a function to the city mediator to return the first building with an open job it finds maybe?

**Comment by Thunder2505** [comment]
@u04576617 We can do it like that... I was just afraid to implement stuff like that in the base design pattern, since it might make Unit tests a bit harder, since then we have more things happening constantly, but if you have an idea of how to do it, I don't have a problem with it

**Comment by u04576617** [comment]
Cool cool, I'll see if there is a way of getting that to work, if not we try something else.
