### ISSUE TITLE
Citizens Require Services

### ISSUE THREAD

**Issue by u04576617** [COS214-Project-2024/WorksOnMyMachineTeam#22]
Citizens should require services
- [x] Healthcare
- [x] Education
- [x] Security
- [x] Entertainment
- [x] Services should affect emotional state

**Comment by Thunder2505** [comment]
We can have it that the happiness for each citizen is decreased by a constant amount till the services are added

**Comment by u04576617** [comment]
> We can have it that the happiness for each citizen is decreased by a constant amount till the services are added

Good idea, the more services required the faster it declines.

**Comment by u04576617** [comment]
@Thunder2505 How are you thinking we should check if the citizens' needs are required?
