### ISSUE TITLE
Traffic System

### ISSUE THREAD

**Issue by u04576617** [COS214-Project-2024/WorksOnMyMachineTeam#27]
The Traffic system should affect the following:
- [x] Traffic flow
- [x] City connectivity
- [x] Commute times 
- [x] Update road state
- [x] Buses can pick up citizens along the route
- [x] Citizen States
- [x] There should be a system in place to calculate congestion in a road and how it decreases over time.

**Comment by u04576617** [comment]
@Amber21457752 I think we should implement the transport the way I mentioned it in the demo:
- Different roads have a different "capacity"
- Traffic depends on how full the roads are

This should be fairly simple to add, and it'll work really nice with our turn based system. After citizen states are calculated, we can "process" traffic, allowing citizens to move to a road closer to their destination (or eventually arrive at their destination). This way we have commute times right from the start.

**Comment by Amber21457752** [comment]
Yes, i agree with this implementation. It's a very straight forward system, but it will also make it seem a little more realistic.

**Comment by u04576617** [comment]
@Amber21457752 I'm going to mark off Traffic flow, City connectivity and Commute times. I have implemented a "bus" system where citizens without cars can request a bus to and from work. I still need to update a few things but the basic functionality is there. Roads now have a set capacity for cars, thus we can have traffic build up.
